apiVersion: apps/v1
kind: Deployment
metadata:
  name: lvg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lvg-app
  template:
    metadata:
      labels:
        app: lvg-app
    spec:
      containers:
      - name: lvg-app
        image: localhost:5001/lvg-app:latest
        ports:
        - containerPort: 5000
        env:
          - name: POSTGRES_HOST
            value: "postgres"         # This should match your PostgreSQL service name
          - name: POSTGRES_PORT
            value: "5432"             # The default PostgreSQL port
          - name: POSTGRES_USER
            value: "postgres"         # Username set during deployment
          - name: POSTGRES_PASSWORD
            value: "mysecretpassword" # Password set during deployment
          - name: POSTGRES_DB
            value: "postgres"         # Your database name
---
apiVersion: v1
kind: Service
metadata:
  name: lvg-app
spec:
  selector:
    app: lvg-app
  ports:
    - protocol: TCP
      port: 80        # External port to expose
      targetPort: 5000 # The port your Flask app is running on inside the pod
  type: ClusterIP
---
# postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

