name = "difference-engine"
main = "src/index.js"
compatibility_date = "2026-05-29"

[assets]
directory = "./site"
binding = "ASSETS"

[[containers]]
class_name = "Backend"
image = "./Dockerfile"
max_instances = 1

[[durable_objects.bindings]]
class_name = "Backend"
name = "BACKEND"

[[migrations]]
new_sqlite_classes = [ "Backend" ]
tag = "v1"

[observability]
enabled = true
